---
os_nodes: |-
        {% for item in groups['os-cluster'] -%}
          {{ hostvars[item]['ip'] }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

populate_inventory_to_hosts_file: true

logstash_home: /usr/share/logstash
logstash_conf_dir: /usr/share/logstash/config
logstash_pipeline_dir: /usr/share/logstash/pipeline
logstash_user: logstash

os_api_port: 9500
os_nodes_logstash: |-
        {% for item in groups['os-cluster'] -%}
          https://{{ hostvars[item]['ip'] }}:{{ os_api_port }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

systemctl_path: /etc/systemd/system
