---

- name: Logstash Install | Download logstash OSS {{ logstash_version }}
  get_url:
    url: "{{ logstash_download_url }}/logstash-oss-with-opensearch-output-plugin-{{ logstash_version }}-linux-x64.tar.gz"
    dest: "/tmp/logstash.tar.gz"
  register: download

- name: Logstash Install | Create logstash_user user
  user:
    name: "{{ logstash_user }}"
    state: present
    shell: /bin/bash
  # when: download.changed

- name: Logstash Install | Create home directory
  file:
    path: "{{ logstash_home }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
  # when: download.changed

- name: Logstash Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf logstash.tar.gz -C "{{ logstash_home }}" --strip-components=1
  # when: download.changed

- name: Logstash Install | Make data dir readable
  command: chmod 666 {{ logstash_home }}/data
  # when: download.changed

#- name: Logstash Install | Create NTT config dir
#  command: mkdir {{ ntt_conf_dir }}à 
  # when: download.changed

- name: Logstash Mock Pipeline | Copy Configuration File
  template:
    src: pipelines.yml
    dest: "{{logstash_conf_dir}}/pipelines.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
    mode: 0644
    backup: yes
  # when: download.changed  

- name: Logstash System Options | Copy Configuration File
  template:
    src: startup.options
    dest: "{{ logstash_conf_dir }}/startup.options"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
    mode: 0644
    backup: yes
  # when: download.changed  

- name: Logstash Install | Run system-install script
  command: "{{ logstash_home }}/bin/system-install"
