---

- name: Logstash Install | Download logstash OSS {{ logstash_version }}
  get_url:
    url: "{{ logstash_download_url }}/logstash-oss-with-opensearch-output-plugin-{{ logstash_version }}-linux-x64.tar.gz"
    dest: "/tmp/logstash.tar.gz"
  register: download

- name: Logstash Install | Create opensearch user
  user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/bash
  # when: download.changed

- name: Logstash Install | Create home directory
  file:
    path: "{{ logstash_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
  # when: download.changed

- name: Logstash Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf logstash.tar.gz -C "{{ logstash_home }}" --strip-components=1
  # when: download.changed

- name: Logstash Install | Make data dir readable
  command: chmod 666 {{ logstash_home }}/data
  # when: download.changed

- name: Logstash Install | Create NTT config dir
  command: mkdir {{ ntt_conf_dir }} 
  # when: download.changed

- name: Logstash Mock Pipeline | Copy Configuration File
  template:
    src: logstash-test.conf
    dest: "{{ntt_conf_dir}}/logstash-test.conf"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0644
    backup: yes
  # when: download.changed  

- name: Logstash Install | create systemd service
  template:
    src: logstash.service
    dest: "{{ systemctl_path }}/logstash.service"
  # when: download.changed  
