---

- name: Logstash Install | [OnLine] Download logstash OSS {{ logstash_version }} (URL={{ logstash_download_url }})
  get_url:
    url: "{{ logstash_download_url }}"
    dest: "/tmp/logstash.tar.gz"
  register: online_download
  when: not offline_installation

- name: Logstash Install | [OffLine] Create local temporary directory for zip download
  local_action:
    module: file
    path: "{{ temp_tar_dir }}"
    state: directory
  run_once: true
  when: offline_installation

- name: Logstash Install | [OffLine] Download logstash OSS {{ logstash_version }} (URL={{ logstash_download_url }})
  delegate_to: localhost
  get_url:
    url: "{{ logstash_download_url }}"
    dest: "{{ temp_tar_dir }}"
  register: offline_download
  when: offline_installation

- name: Logstash Install | [OffLine] Copy logstash OSS tar through ssh
  copy:
    src: "{{ temp_tar_dir }}/logstash-oss-with-opensearch-output-plugin-{{ logstash_version }}-linux-x64.tar.gz"
    dest: "/tmp/logstash.tar.gz"
    group: "{{ os_user }}"
    owner: "{{ os_user }}"
  run_once: true
  when: 
    - offline_installation
    - offline_download.changed

- name: Logstash Install | Create logstash user
  user:
    name: "{{ logstash_user }}"
    state: present
    shell: /bin/bash
  when: (online_download.changed) or (offline_download.changed)

- name: Logstash Install | Create home directory
  file:
    path: "{{ logstash_home }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
  when: (online_download.changed) or (offline_download.changed)

- name: Logstash Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf logstash.tar.gz -C "{{ logstash_home }}" --strip-components=1
  when: (online_download.changed) or (offline_download.changed)

- name: Logstash Install | Update data directory
  file:
    path: "{{ logstash_home }}/data"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
  when: (online_download.changed) or (offline_download.changed)

- name: Logstash Install | Remove sample pipeline in config dir
  command: rm --force {{ logstash_conf_dir }}/logstash-sample.conf
  when: (online_download.changed) or (offline_download.changed)  

- name: Logstash Install | Create pipeline directory {{ logstash_pipeline_dir }}
  file:
    path: "{{ logstash_pipeline_dir }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
  when: (online_download.changed) or (offline_download.changed)  

- name: Logstash Install | Copy logstash-sample.conf in {{ logstash_pipeline_dir }}
  template:
    src: logstash-sample.conf
    dest: "{{ logstash_pipeline_dir }}/logstash-sample.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
    mode: 0644
    backup: no
  when: (online_download.changed) or (offline_download.changed)    

- name: Logstash Install | Copy (and backup) startup.options File in {{ logstash_conf_dir }}
  template:
    src: startup.options
    dest: "{{ logstash_conf_dir }}/startup.options"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
    mode: 0644
    backup: yes
  when: (online_download.changed) or (offline_download.changed)  

- name: Logstash Install | Run system-install script
  command: "{{ logstash_home }}/bin/system-install"
