---

- name: OpenSearch Install | [OnLine] Download opensearch {{ os_version }} (URL={{ opensearch_download_url }})
  get_url:
    url: "{{ opensearch_download_url }}"
    dest: "/tmp/opensearch.tar.gz"
  register: online_download
  when: not offline_installation

- name: OpenSearch Install | [OffLine] Create local temporary directory for zip download
  local_action:
    module: file
    path: "{{ temp_tar_dir }}"
    state: directory
  run_once: true
  when: offline_installation

- name: OpenSearch Install | [OffLine] Download opensearch {{ os_version }} (URL={{ opensearch_download_url }})
  delegate_to: localhost
  get_url:
    url: "{{ opensearch_download_url }}"
    dest: "{{ temp_tar_dir }}"
  register: offline_download
  when: offline_installation

- name: OpenSearch Install | [OffLine] Copy Opensearch tar through ssh
  copy:
    src: "{{ temp_tar_dir }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch.tar.gz"
    group: "{{ os_user }}"
    owner: "{{ os_user }}"
  run_once: true
  when: 
    - offline_installation
    - offline_download.changed

- name: OpenSearch Install | Create opensearch user
  user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/bash
  when: (online_download.changed) or (offline_download.changed)

- name: OpenSearch Install | Create home directory
  file:
    path: "{{ os_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
  when: (online_download.changed) or (offline_download.changed)

- name: OpenSearch Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf opensearch.tar.gz -C "{{ os_home }}" --strip-components=1
  when: (online_download.changed) or (offline_download.changed)

- name: OpenSearch Install | Copy Configuration File
  template:
    src: "opensearch-{{ cluster_type }}.yml"
    dest: "{{os_conf_dir}}/opensearch.yml"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    backup: yes

- name: OpenSearch Install | Copy jvm.options File for Instance
  template:
    src: jvm.options
    dest: "{{os_conf_dir}}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    force: yes

- name: OpenSearch Install | create systemd service
  template:
    src: opensearch.service
    dest: "{{ systemctl_path }}/opensearch.service"
