## Common opensearch configuration parameters ##

os_cluster_name: development-cluster

# opensearch download
os_download_url: https://artifacts.opensearch.org/releases/bundle/opensearch

# https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-7.16.2-linux-x64.tar.gz
logstash_download_url: https://artifacts.opensearch.org/logstash

# opensearch version
os_version: "1.2.2"

# opensearch dashboards version
os_dashboards_version: "1.2.0"

#logstash version
logstash_version: "7.16.2"

# Configure hostnames for opensearch nodes
# It is required to configure SSL
# Example es1.example.com, es2.example.com
domain_name: example.com

os_user: opensearch

# Java memory heap values(GB) for opensearch
# You can change it based on server specs
xms_value: 2
xmx_value: 2

# Cluster type whether its single node or multi-node
cluster_type: multi-node
